name: Flutter CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  # ========== ANDROID ==========
  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get
      - run: |
          # build release apks

          ## environment setup

          app_ver=$(grep 'version:' pubspec.yaml)
          app_ver=$(echo "${app_ver/'version:'/}" | xargs)
          app_ver="${app_ver%%+*}"
          echo "v$app_ver"
          echo "app_ver=$app_ver" >> $GITHUB_ENV

          mkdir artifacts && {
            ARTIFACTS_PATH="$GITHUB_WORKSPACE/artifacts"
            echo "ARTIFACTS_PATH=$ARTIFACTS_PATH" >> $GITHUB_ENV
          }

          echo "$JAVA_KEYSTORE" | base64 -d > android/app/New_Keystore.jks
          echo "$JAVA_KEYSTORE_PROPERTIES" | base64 -d > android/keystore.properties
          echo "$PAYMOB_KEYS" | base64 -d >keys.json

          ## build

          flutter pub get

          flutter build apk --release --split-per-abi --obfuscate --split-debug-info=build/android/split_symbols --dart-define-from-file=keys.json
          (cd ./build/app/outputs/flutter-apk/ && {
            mv ./app-arm64-v8a-release.apk "$ARTIFACTS_PATH/$APP_NAME-$app_ver-arm64-v8a.apk"
            mv ./app-armeabi-v7a-release.apk "$ARTIFACTS_PATH/$APP_NAME-$app_ver-armeabi-v7a.apk"
            mv ./app-x86_64-release.apk "$ARTIFACTS_PATH/$APP_NAME-$app_ver-x86_64.apk"
          })

          flutter build apk --release --obfuscate --split-debug-info=build/android/symbols --dart-define-from-file=keys.json
          (cd ./build/app/outputs/flutter-apk/ &&
            mv ./app-release.apk "$ARTIFACTS_PATH/$APP_NAME-$app_ver-universal.apk"
          )

          rm -rf ./build/app/outputs/apk # remove dupe apk dir
        shell: bash
        env:
          JAVA_KEYSTORE: ${{ secrets.JAVA_KEYSTORE }}
          JAVA_KEYSTORE_PROPERTIES: ${{ secrets.JAVA_KEYSTORE_PROPERTIES }}
          PAYMOB_KEYS: ${{ secrets.PAYMOB_KEYS }}
          APP_NAME: ${{ github.event.repository.name }}

      - name: Upload Android Artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.ARTIFACTS_PATH }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  # ========== IOS ==========
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get
      - name: Build Simulator iOS IPA
        run: |
          echo "$PAYMOB_KEYS" | base64 -d >keys.json
          flutter build ios --simulator --no-codesign --obfuscate --split-debug-info=build/ios/symbols --dart-define-from-file=keys.json
          mkdir artifacts
          cd build/ios/iphonesimulator
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ios-app-simulator-unsigned.ipa Payload
          mv ios-app-simulator-unsigned.ipa ../../../artifacts/
        env:
          PAYMOB_KEYS: ${{ secrets.PAYMOB_KEYS }}

      - name: Upload iOS Artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  # ========== WEB ==========
  web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: |
          echo "$PAYMOB_KEYS" | base64 -d >keys.json
          flutter pub get
          flutter build web --release --dart-define-from-file=keys.json --base-href /fakestore-e-commerce-flutter/
        env:
          PAYMOB_KEYS: ${{ secrets.PAYMOB_KEYS }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages